In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.1

In [2]:
data = {
    "name":    ["Alice", "Bob", "Carol", "Dave"],
    "revenue": [1200, 800, 1500, 600],
    "region":  ["North", "South", "North", "South"]
}

df = pd.DataFrame(data)
df

    name  revenue region
0  Alice     1200  North
1    Bob      800  South
2  Carol     1500  North
3   Dave      600  South

In [3]:
print("Type:", type(df))
print("Shape:", df.shape)
print("Dtypes:\n", df.dtypes)
print("Index:", df.index)

Type: <class 'pandas.DataFrame'>
Shape: (4, 3)
Dtypes:
 name         str
revenue    int64
region       str
dtype: object
Index: RangeIndex(start=0, stop=4, step=1)

In [4]:
# Sort to make the difference visible
print(df)
print("\n")
df_sorted = df.sort_values("revenue", ascending=False)

print("Sorted DataFrame:")
print(df_sorted)
print("\nilocl[0] - by position:", df_sorted.iloc[0]["name"])
print("loc[0] - by label:", df_sorted.loc[0]["name"])

    name  revenue region
0  Alice     1200  North
1    Bob      800  South
2  Carol     1500  North
3   Dave      600  South


Sorted DataFrame:
    name  revenue region
2  Carol     1500  North
0  Alice     1200  North
1    Bob      800  South
3   Dave      600  South

ilocl[0] - by position: Carol
loc[0] - by label: Alice

In [5]:
df_sorted = df.sort_values("revenue", ascending=False).reset_index(drop=True)

print(df_sorted)
print("\nAfter reset - iloc[0]:", df_sorted.iloc[0]["name"])
print("After reset - loc[0]:", df_sorted.loc[0]["name"])

    name  revenue region
0  Carol     1500  North
1  Alice     1200  North
2    Bob      800  South
3   Dave      600  South

After reset - iloc[0]: Carol
After reset - loc[0]: Carol

In [ ]:
# Boolean mask
print(df)
print('\n')
mask = df["revenue"] > 1000
print("Mask:")
print(mask)

print("\nFiltered DataFrame:")
print(df[mask])

# Combined conditions
print("\nRevenue > 1000 AND region == North:")
print(df[(df["revenue"] > 1000) & (df["region"] == "North")])

# Using .query()
print("\nSame with .query():")
print(df.query("revenue > 1000 and region == 'North'"))

# Filter + select specific columns
print("\nFilter + select columns with .loc:")
print(df.loc[df["revenue"] > 1000, ["name", "revenue"]])

    name  revenue region
0  Alice     1200  North
1    Bob      800  South
2  Carol     1500  North
3   Dave      600  South


Mask:
0     True
1    False
2     True
3    False
Name: revenue, dtype: bool

Filtered DataFrame:
    name  revenue region
0  Alice     1200  North
2  Carol     1500  North

Revenue > 1000 AND region == North:
    name  revenue region
0  Alice     1200  North
2  Carol     1500  North

Same with .query():
    name  revenue region
0  Alice     1200  North
2  Carol     1500  North

Filter + select columns with .loc:
    name  revenue
0  Alice     1200
2  Carol     1500

In [7]:
data2 = {
    "name":     ["Alice", "Bob", "Carol", "Dave", "Eve"],
    "region":   ["North", "South", "North", "South", "North"],
    "revenue":  [1200, 800, 1500, 600, 900],
    "category": ["A", "B", "A", "B", "B"]
}

df2 = pd.DataFrame(data2)
df2

    name region  revenue category
0  Alice  North     1200        A
1    Bob  South      800        B
2  Carol  North     1500        A
3   Dave  South      600        B
4    Eve  North      900        B

In [8]:
# Total revenue per region
print("Total revenue per region:")
print(df2.groupby("region")["revenue"].sum())

Total revenue per region:
region
North    3600
South    1400
Name: revenue, dtype: int64

In [9]:
# sum, mean, count in one shot
print("Multiple aggregations:")
print(df2.groupby("region")["revenue"].agg(["sum", "mean", "count"]))

Multiple aggregations:
         sum    mean  count
region
North   3600  1200.0      3
South   1400   700.0      2

In [10]:
# Group by region AND category
print("Revenue by region and category:")
print(df2.groupby(["region", "category"])["revenue"].sum())

Revenue by region and category:
region  category
North   A           2700
        B            900
South   B           1400
Name: revenue, dtype: int64

In [12]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Carol", "Dave"]
})

orders = pd.DataFrame({
    "order_id":    [101, 102, 103, 104, 105],
    "customer_id": [1, 2, 2, 3, 5],  # notice: 4 is missing, 5 doesn't exist
    "amount":      [250, 150, 300, 175, 200]
})

print("Customers:")
print(customers)
print("\nOrders:")
print(orders)

Customers:
   customer_id   name
0            1  Alice
1            2    Bob
2            3  Carol
3            4   Dave

Orders:
   order_id  customer_id  amount
0       101            1     250
1       102            2     150
2       103            2     300
3       104            3     175
4       105            5     200

In [16]:
customers

   customer_id   name
0            1  Alice
1            2    Bob
2            3  Carol
3            4   Dave

In [14]:
orders

   order_id  customer_id  amount
0       101            1     250
1       102            2     150
2       103            2     300
3       104            3     175
4       105            5     200

In [15]:
# INNER JOIN - only matching rows on both sides
inner = pd.merge(customers, orders, on="customer_id", how="inner")
print("INNER JOIN:")
print(inner)

# LEFT JOIN - all customers, even if no orders
left = pd.merge(customers, orders, on="customer_id", how="left")
print("\nLEFT JOIN:")
print(left)

# RIGHT JOIN - all orders, even if customer doesn't exist
right = pd.merge(customers, orders, on="customer_id", how="right")
print("\nRIGHT JOIN:")
print(right)

# OUTER JOIN - everything from both sides
outer = pd.merge(customers, orders, on="customer_id", how="outer")
print("\nOUTER JOIN:")
print(outer)

INNER JOIN:
   customer_id   name  order_id  amount
0            1  Alice       101     250
1            2    Bob       102     150
2            2    Bob       103     300
3            3  Carol       104     175

LEFT JOIN:
   customer_id   name  order_id  amount
0            1  Alice     101.0   250.0
1            2    Bob     102.0   150.0
2            2    Bob     103.0   300.0
3            3  Carol     104.0   175.0
4            4   Dave       NaN     NaN

RIGHT JOIN:
   customer_id   name  order_id  amount
0            1  Alice       101     250
1            2    Bob       102     150
2            2    Bob       103     300
3            3  Carol       104     175
4            5    NaN       105     200

OUTER JOIN:
   customer_id   name  order_id  amount
0            1  Alice     101.0   250.0
1            2    Bob     102.0   150.0
2            2    Bob     103.0   300.0
3            3  Carol     104.0   175.0
4            4   Dave       NaN     NaN
5            5    NaN     105.0   200.0

In [17]:
wide_df = pd.DataFrame({
    "name":      ["Alice", "Bob"],
    "jan_sales": [1200, 800],
    "feb_sales": [1500, 900],
    "mar_sales": [1100, 750]
})

print("Wide format:")
print(wide_df)

# melt - convert wide to long
long_df = wide_df.melt(
    id_vars="name",        # column to keep as identifier
    var_name="month",      # name for the new column headers column
    value_name="sales"     # name for the values column
)

print("\nLong format:")
print(long_df)

Wide format:
    name  jan_sales  feb_sales  mar_sales
0  Alice       1200       1500       1100
1    Bob        800        900        750

Long format:
    name      month  sales
0  Alice  jan_sales   1200
1    Bob  jan_sales    800
2  Alice  feb_sales   1500
3    Bob  feb_sales    900
4  Alice  mar_sales   1100
5    Bob  mar_sales    750

In [18]:
# Using the long_df we just created
print("Long format (input):")
print(long_df)

# pivot_table - convert long to wide
pivot_df = long_df.pivot_table(
    index="name",      # what becomes the row labels
    columns="month",   # what becomes the column headers
    values="sales"     # what fills the cells
)

print("\nWide format (output):")
print(pivot_df)

Long format (input):
    name      month  sales
0  Alice  jan_sales   1200
1    Bob  jan_sales    800
2  Alice  feb_sales   1500
3    Bob  feb_sales    900
4  Alice  mar_sales   1100
5    Bob  mar_sales    750

Wide format (output):
month  feb_sales  jan_sales  mar_sales
name
Alice     1500.0     1200.0     1100.0
Bob        900.0      800.0      750.0

In [19]:
# Realistic employee performance data
# Multiple metrics per person per month
wide_data = pd.DataFrame({
    "name":           ["Alice", "Bob", "Carol", "Dave", "Eve"],
    "region":         ["North", "South", "North", "South", "North"],
    "department":     ["Sales", "Sales", "Marketing", "Marketing", "Sales"],
    "jan_sales":      [1200, 800, 1500, 600, 900],
    "feb_sales":      [1500, 900, 1700, 750, 1100],
    "mar_sales":      [1100, 750, 1300, 500, 950],
    "jan_calls":      [45, 30, 55, 20, 35],
    "feb_calls":      [50, 35, 60, 25, 40],
    "mar_calls":      [48, 32, 58, 22, 38],
    "jan_satisfaction":[4.2, 3.8, 4.5, 3.5, 4.0],
    "feb_satisfaction":[4.4, 3.9, 4.6, 3.7, 4.1],
    "mar_satisfaction":[4.3, 4.0, 4.7, 3.6, 4.2],
})

print("Wide format:")
print(wide_data)
print(f"\nShape: {wide_data.shape}")

Wide format:
    name region department  jan_sales  feb_sales  mar_sales  jan_calls  \
0  Alice  North      Sales       1200       1500       1100         45
1    Bob  South      Sales        800        900        750         30
2  Carol  North  Marketing       1500       1700       1300         55
3   Dave  South  Marketing        600        750        500         20
4    Eve  North      Sales        900       1100        950         35

   feb_calls  mar_calls  jan_satisfaction  feb_satisfaction  mar_satisfaction
0         50         48               4.2               4.4               4.3
1         35         32               3.8               3.9               4.0
2         60         58               4.5               4.6               4.7
3         25         22               3.5               3.7               3.6
4         40         38               4.0               4.1               4.2

Shape: (5, 12)

In [20]:
# You can choose WHICH columns to melt
# id_vars = columns to keep as-is
long_sales = wide_data.melt(
    id_vars=["name", "region", "department"],  # keep these fixed
    value_vars=["jan_sales", "feb_sales", "mar_sales"],  # only melt these
    var_name="month",
    value_name="sales"
)

print("Long format - sales only:")
print(long_sales)
print(f"\nShape: {long_sales.shape}")

Long format - sales only:
     name region department      month  sales
0   Alice  North      Sales  jan_sales   1200
1     Bob  South      Sales  jan_sales    800
2   Carol  North  Marketing  jan_sales   1500
3    Dave  South  Marketing  jan_sales    600
4     Eve  North      Sales  jan_sales    900
5   Alice  North      Sales  feb_sales   1500
6     Bob  South      Sales  feb_sales    900
7   Carol  North  Marketing  feb_sales   1700
8    Dave  South  Marketing  feb_sales    750
9     Eve  North      Sales  feb_sales   1100
10  Alice  North      Sales  mar_sales   1100
11    Bob  South      Sales  mar_sales    750
12  Carol  North  Marketing  mar_sales   1300
13   Dave  South  Marketing  mar_sales    500
14    Eve  North      Sales  mar_sales    950

Shape: (15, 5)

In [21]:
# Pivot sales back to wide
pivot_back = long_sales.pivot_table(
    index=["name", "region", "department"],  # multiple index columns
    columns="month",
    values="sales"
)

print("Pivoted back:")
print(pivot_back)

Pivoted back:
month                    feb_sales  jan_sales  mar_sales
name  region department
Alice North  Sales          1500.0     1200.0     1100.0
Bob   South  Sales           900.0      800.0      750.0
Carol North  Marketing      1700.0     1500.0     1300.0
Dave  South  Marketing       750.0      600.0      500.0
Eve   North  Sales          1100.0      900.0      950.0

In [22]:
import numpy as np

df_missing = pd.DataFrame({
    "name":     ["Alice", "Bob", "Carol", "Dave", "Eve"],
    "region":   ["North", None, "North", "South", None],
    "revenue":  [1200, 800, None, 600, 900],
    "category": ["A", "B", "A", None, "B"]
})

print(df_missing)
print("\nMissing values per column:")
print(df_missing.isna().sum())
print(f"\nTotal missing: {df_missing.isna().sum().sum()}")

    name region  revenue category
0  Alice  North   1200.0        A
1    Bob    NaN    800.0        B
2  Carol  North      NaN        A
3   Dave  South    600.0      NaN
4    Eve    NaN    900.0        B

Missing values per column:
name        0
region      2
revenue     1
category    1
dtype: int64

Total missing: 4

In [23]:
df_filled = df_missing.copy()  # always work on a copy, never modify raw data

# Fill revenue with median - meaningful for numeric columns
df_filled["revenue"] = df_filled["revenue"].fillna(df_filled["revenue"].median())

# Fill region with mode (most common value)
df_filled["region"] = df_filled["region"].fillna(df_filled["region"].mode()[0])

# Fill category with a literal string
df_filled["category"] = df_filled["category"].fillna("Unknown")

print("After filling:")
print(df_filled)
print("\nMissing values remaining:")
print(df_filled.isna().sum())

After filling:
    name region  revenue category
0  Alice  North   1200.0        A
1    Bob  North    800.0        B
2  Carol  North    850.0        A
3   Dave  South    600.0  Unknown
4    Eve  North    900.0        B

Missing values remaining:
name        0
region      0
revenue     0
category    0
dtype: int64

In [24]:
# Drop rows where ANY column is null
print("Drop any null:")
print(df_missing.dropna())

# Drop rows where ALL columns are null
print("\nDrop only if ALL null:")
print(df_missing.dropna(how="all"))

# Drop rows where specific column is null
# Use this when that column is critical to your pipeline
print("\nDrop only where revenue is null:")
print(df_missing.dropna(subset=["revenue"]))

Drop any null:
    name region  revenue category
0  Alice  North   1200.0        A

Drop only if ALL null:
    name region  revenue category
0  Alice  North   1200.0        A
1    Bob    NaN    800.0        B
2  Carol  North      NaN        A
3   Dave  South    600.0      NaN
4    Eve    NaN    900.0        B

Drop only where revenue is null:
    name region  revenue category
0  Alice  North   1200.0        A
1    Bob    NaN    800.0        B
3   Dave  South    600.0      NaN
4    Eve    NaN    900.0        B

In [27]:
df3 = pd.DataFrame({
    "name":     ["Alice", "Bob", "Carol", "Dave"],
    "revenue":  [1200, 800, 1500, 600],
    "region":   ["North", "South", "North", "South"]
})

# WRONG — chained indexing, may silently fail
df3[df3["region"] == "North"]["revenue"] = 9999
print("After chained assignment (WRONG way):")
print(df3)  # revenue did NOT change — silent failure

# RIGHT — always use .loc for assignments
df3.loc[df3["region"] == "North", "revenue"] = 9999
print("\nAfter .loc assignment (RIGHT way):")
print(df3)  # revenue changed correctly

After chained assignment (WRONG way):
    name  revenue region
0  Alice     1200  North
1    Bob      800  South
2  Carol     1500  North
3   Dave      600  South

After .loc assignment (RIGHT way):
    name  revenue region
0  Alice     9999  North
1    Bob      800  South
2  Carol     9999  North
3   Dave      600  South

C:\Users\60403\AppData\Local\Temp\ipykernel_23784\1377238979.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df3[df3["region"] == "North"]["revenue"] = 9999

In [34]:
import pandas as pd

# Realistic sales rep data
df_sales = pd.DataFrame({
    "name":       ["Alice", "Bob", "Carol", "Dave", "Eve"],
    "revenue":    [1200, 800, 1500, 600, 900],
    "region":     ["North", "South", "North", "South", "North"],
    "experience": [5, 2, 8, 1, 3],   # years of experience
    "rating":     [4.2, 3.8, 4.7, 3.2, 4.0]  # performance rating
})

df_sales

    name  revenue region  experience  rating
0  Alice     1200  North           5     4.2
1    Bob      800  South           2     3.8
2  Carol     1500  North           8     4.7
3   Dave      600  South           1     3.2
4    Eve      900  North           3     4.0

In [35]:
# Categorize sales reps by revenue performance
def performance_band(revenue):
    if revenue >= 1200:
        return "Top Performer"
    elif revenue >= 800:
        return "On Track"
    else:
        return "Needs Improvement"

df_sales["performance"] = df_sales["revenue"].apply(performance_band)
df_sales

    name  revenue region  experience  rating        performance
0  Alice     1200  North           5     4.2      Top Performer
1    Bob      800  South           2     3.8           On Track
2  Carol     1500  North           8     4.7      Top Performer
3   Dave      600  South           1     3.2  Needs Improvement
4    Eve      900  North           3     4.0           On Track

In [36]:
# Lambda - when the logic is simple enough for one line
df_sales["revenue_in_thousands"] = df_sales["revenue"].apply(lambda x: round(x / 1000, 1))

# Bonus calculation - 10% for top performers, 5% for rest
df_sales["bonus"] = df_sales["revenue"].apply(lambda x: x * 0.10 if x >= 1200 else x * 0.05)

df_sales

,name,revenue,region,experience,rating,performance,revenue_in_thousands,bonus
0,Alice,1200,North,5,4.2,Top Performer,1.2,120.0
1,Bob,800,South,2,3.8,On Track,0.8,40.0
2,Carol,1500,North,8,4.7,Top Performer,1.5,150.0
3,Dave,600,South,1,3.2,Needs Improvement,0.6,30.0
4,Eve,900,North,3,4.0,On Track,0.9,45.0

In [37]:
# Sometimes you need values from MORE than one column
# axis=1 means apply row by row

def eligibility(row):
    # Eligible for promotion if: revenue > 1000 AND experience > 3 AND rating > 4.0
    if row["revenue"] > 1000 and row["experience"] > 3 and row["rating"] > 4.0:
        return "Eligible"
    else:
        return "Not Eligible"

df_sales["promotion"] = df_sales.apply(eligibility, axis=1)
df_sales

,name,revenue,region,experience,rating,performance,revenue_in_thousands,bonus,promotion
0,Alice,1200,North,5,4.2,Top Performer,1.2,120.0,Eligible
1,Bob,800,South,2,3.8,On Track,0.8,40.0,Not Eligible
2,Carol,1500,North,8,4.7,Top Performer,1.5,150.0,Eligible
3,Dave,600,South,1,3.2,Needs Improvement,0.6,30.0,Not Eligible
4,Eve,900,North,3,4.0,On Track,0.9,45.0,Not Eligible

In [38]:
# map() is simpler than apply() - just replaces values using a dictionary
# Perfect for encoding or renaming categories

region_map = {
    "North": "Northern Region",
    "South": "Southern Region"
}

df_sales["region_full"] = df_sales["region"].map(region_map)
df_sales

,name,revenue,region,experience,rating,performance,revenue_in_thousands,bonus,promotion,region_full
0,Alice,1200,North,5,4.2,Top Performer,1.2,120.0,Eligible,Northern Region
1,Bob,800,South,2,3.8,On Track,0.8,40.0,Not Eligible,Southern Region
2,Carol,1500,North,8,4.7,Top Performer,1.5,150.0,Eligible,Northern Region
3,Dave,600,South,1,3.2,Needs Improvement,0.6,30.0,Not Eligible,Southern Region
4,Eve,900,North,3,4.0,On Track,0.9,45.0,Not Eligible,Northern Region

In [ ]:
df_compare = pd.DataFrame({
    "name":   ["Alice", "Bob", "Carol", "Dave"],
    "region": ["North", "South", "North", "South"],
    "revenue":[1200, 800, 1500, 600]
})

# -----------------------------------------------
# map() — ONLY for replacing/looking up values
# Works on a Series, uses a dictionary or function
# Simple 1-to-1 replacement
# -----------------------------------------------

# USE map() when: you have a known lookup table
region_codes = {"North": "N", "South": "S"}
df_compare["region_code"] = df_compare["region"].map(region_codes)
# "North" → "N", "South" → "S"
# No logic, no conditions, just lookup

print("After map():")
print(df_compare)

# -----------------------------------------------
# apply() — for transformations with logic
# Works on a Series OR whole row (axis=1)
# Can have conditions, calculations, if/else
# -----------------------------------------------

# USE apply() when: you need logic or calculations
df_compare["revenue_band"] = df_compare["revenue"].apply(lambda x: "High" if x >= 1000 else "Low")
# Has a condition — map() can't do this cleanly

print("\nAfter apply():")
print(df_compare)

# -----------------------------------------------
# What happens when map() meets unknown values?
# -----------------------------------------------
region_codes_incomplete = {"North": "N"}  # South is missing!
df_compare["region_code_v2"] = df_compare["region"].map(region_codes_incomplete)

print("\nmap() with missing keys — becomes NaN:")
print(df_compare[["region", "region_code_v2"]])
# South → NaN because it wasn't in the dictionary
# apply() would never do this — it runs the function regardless

After map():
    name region  revenue region_code
0  Alice  North     1200           N
1    Bob  South      800           S
2  Carol  North     1500           N
3   Dave  South      600           S

After apply():
    name region  revenue region_code revenue_band
0  Alice  North     1200           N         High
1    Bob  South      800           S          Low
2  Carol  North     1500           N         High
3   Dave  South      600           S          Low

map() with missing keys — becomes NaN:
  region region_code_v2
0  North              N
1  South            NaN
2  North              N
3  South            NaN